### ISSUE TITLE
bug: High DPI not supported

### ISSUE THREAD

**Issue by trickypr** [marc2332/freya#1]
Application text is too small when compared to other system applications.

<img width="777" alt="Screen Shot 2022-08-30 at 8 31 45 pm" src="https://user-images.githubusercontent.com/23250792/187414950-ad34a46c-1d5f-4fa6-9bed-70b7cebe5aa7.png">

Left: Example application
Right: Color meter for text size reference.

**Comment by marc2332** [comment]
I think this is easy fix.

**Comment by marc2332** [comment]
hi @trickypr do you mind trying https://github.com/marc2332/freya/pull/146 ? This time it should work!
