### ISSUE TITLE
suggestion: make `radius` field name more descriptive

### ISSUE THREAD

**Issue by Tropix126** [marc2332/freya#214]
Right now, `radius` determines the outer rounding of an element's corners, but its name is kind of vague and might instead imply a sizing property rather than a roundness value. CSS uses `border-radius`, although the CSS working group [considers this naming a mistake](https://wiki.csswg.org/ideas/mistakes). Maybe something like `corner_radius` would be more descriptive?

**Comment by marc2332** [comment]
> Right now, `radius` determines the outer rounding of an element's corners, but its name is kind of vague and might instead imply a sizing property rather than a roundness value. CSS uses `border-radius`, although the CSS working group [considers this naming a mistake](https://wiki.csswg.org/ideas/mistakes). Maybe something like `corner_radius` would be more descriptive?

Would it be too crazy to accept both ways? `radius` and `corner_radius`? I don't like having to swap an attribute name hehe, but I understand your proposal
