### ISSUE TITLE
suggestion: Window drag area

### ISSUE THREAD

**Issue by Tropix126** [marc2332/freya#262]
Not sure how support for this in winit looks, but it's probably going to be useful to have a way to mark an element (either through a wrapper component like `CursorArea` or attribute/hook) as a region that the window can be dragged from. This is needed to implement custom window decorations if people choose to disable the titlebar and draw their own.

**Comment by ZeroX-DG** [comment]
In electron app, you can define a drag region using a CSS property:

```
-webkit-app-region: drag;
```

Perhaps we can introduce an `app-region` property for `rect` that does the same thing?

**Comment by ZeroX-DG** [comment]
It's pretty simple to implement this feature as well. I'll draft up a quick PR.

**Comment by marc2332** [comment]
my heart tells me to try to implement it in user-land first, as a component and if that doesn't go well then do it at framework level, I guess an attribute like that could work as well, I wonder how other Rust non-web frameworks do it

**Comment by marc2332** [comment]
> It's pretty simple to implement this feature as well. I'll draft up a quick PR.

I don't think its that easy to implement as it must work nicely with the event system, which makes me think even more it is more worth trying to implement it as a component

**Comment by ZeroX-DG** [comment]
> I don't think its that easy to implement as it must work nicely with the event system,
I did a quick implementation & it seems to work fine. What problem with the event system that you foresee?

**Comment by marc2332** [comment]
> > I don't think its that easy to implement as it must work nicely with the event system,
> 
> I did a quick implementation & it seems to work fine. What problem with the event system that you foresee?

Just event propagation and capturing, open the PR and I'll take a look asap :)

**Comment by ZeroX-DG** [comment]
To be fair, introducing a property to `rect` would also break the consistency with `CursorArea`. You could argue that if we were to introduce this property to `rect`, then we might as well introduce a `cursor_icon` property for `rect` 😄 

Maybe adding a `property` to `CursorArea` is the better way.
