### ISSUE TITLE
bug: Label measurement becomes buggy at certain viewport sizes

### ISSUE THREAD

**Issue by Tropix126** [marc2332/freya#273]
There are two bugs I discovered regarding the `label` element's layout.
1. Resizing the viewport to a certain width range causes it to suddenly jump to a small width.
2. Wrapped labels are not remeasured from their original line-height, meaning that they will overlap elements once they are wrapped.

Top is a `label` element, bottom is a `paragraph` and `text` element.
https://github.com/marc2332/freya/assets/42101043/b23f7bd7-e6ac-4729-a72e-0385ec778bf0

**Comment by marc2332** [comment]
> There are two bugs I discovered regarding the `label` element's layout.
> 
> 1. Resizing the viewport to a certain width range causes it to suddenly jump to a small width.
> 2. Wrapped labels are not remeasured from their original line-height, meaning that they will overlap elements once they are wrapped.
> 
> Top is a `label` element, bottom is a `paragraph` and `text` element. https://github.com/marc2332/freya/assets/42101043/b23f7bd7-e6ac-4729-a72e-0385ec778bf0

Share me the example code

**Comment by Tropix126** [comment]
```rs
fn app(cx: Scope) -> Element {
    let mut count = use_state(cx, || 0);

    render!(
        rect {
            height: "100%",
            width: "100%",
            background: "black",
            color: "white",
            padding: "12",
            onclick: move |_| count += 1,
            label {
                "Click to increase AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaa!"
            }
            rect {
                height: "80",
            }
            paragraph {
                text {
                    "Click to increase AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaa!"
                }
            }
        }
    )
}```

**Comment by marc2332** [comment]
It works fine for me, have you made any changes?
![image](https://github.com/marc2332/freya/assets/38158676/8fb61759-dd55-452a-8b0b-fa78f36628c8)

**Comment by Tropix126** [comment]
I guess I did? After trying the repro again today it works fine 😅. I'll double check all of the branches I was working off of to double check.

**Comment by marc2332** [comment]
hehe, weird, no problem :D
