### ISSUE TITLE
enhancement: `requestAnimationFrame` equivalent

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#322]
Make animations run based on ticker provided by the event loop, this way the animations run on sync with the renderer FPS

- Equivalent of https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
- Take a look at https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html

**Comment by matthunz** [comment]
I think something like https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame would be perfect here. I had some success using https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html to send new frames when they're available. That way animations can use async and request new frames when needed

**Comment by marc2332** [comment]
> I think something like https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame would be perfect here.

Yeah! I just noticed I already have an issue opened https://github.com/marc2332/freya/issues/159 😂 

> I had some success using https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html to send new frames when they're available. That way animations can use async and request new frames when needed

Nice, I'll note that!
