### ISSUE TITLE
enhancement: Password mode for `Input` component

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#324]
Password mode for Input component

**Comment by madara-uchihaaa** [comment]
May you explain more about the task , like what, which input component require password mode ?

**Comment by marc2332** [comment]
> May you explain more about the task , like what, which input component require password mode ?

The idea is to have something like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password for [Input](https://github.com/marc2332/freya/blob/main/crates/components/src/input.rs) so it shows "************" instead of "coolpassword" for example. I imagine the mode as a prop for the component in the form of an enum with two variants, `Normal` and `Password`.

**Comment by OlshaMB** [comment]
Made a pr #325
