### ISSUE TITLE
enhancement: Alignment in rect

### ISSUE THREAD

**Issue by OlshaMB** [marc2332/freya#326]
I need an ability to align items in a rect just like in css you can use `justify-items` and  `align-items` in flexbox, i suggest making align-x and align-y instead of confusing css naming.
Also I saw `center` option of `display` property, but it's behavior is confusing, but also it provides only limited ability to align items, also does it make children absolute?

**Comment by marc2332** [comment]
> I need an ability to align items in a rect just like in css you can use justify-items and align-items in flexbox, i suggest making align-x and align-y instead of confusing css naming.

Yes! That's something I would like to add in the future. https://github.com/marc2332/freya/issues/20

> Also I saw center option of display property, but it's behavior is confusing, but also it provides only limited ability to align items, also does it make children absolute?

The `display` attribute is still very simple, it only allows you to center or not the inner children, with the help of the `direction` attribute. You usually want a single child when using `display: "center"` in the parent, it will make the child center relatively to the parent.

**Comment by OlshaMB** [comment]
Thanks for answering my question and I am closing this as duplicate of #20
