### ISSUE TITLE
enhancement: Remove or replace selected text

### ISSUE THREAD

**Issue by katyo** [marc2332/freya#356]
Usually selection has higher priority than cursor so input behavior should be little bit different if text has been selected.

1. If you select the text and press backspace the selected text expected to be deleted but currently only character before last cursor position deteles.

2. If you select the text and type something other the selected text expected to be replaced by typed but currently new text inserts after cursor position in same time selected text stay not deleted.

![input-selection-behavior](https://github.com/marc2332/freya/assets/238571/bf12e8d2-7fc2-4a1b-82da-0c1a7e6952c0)

**Comment by katyo** [comment]
@marc2332 Seems this issue related to #91. Could you add it to tracking?

**Comment by marc2332** [comment]
Yeah, I was aware of this, it's not really  a bug, it's just not implemented yet hahaha. I Just added it to the tracking issue! :smile:

**Comment by marc2332** [comment]
I recently added support for removing the selected when using Delete or backspace, I'll soon make it possible to replace it with the new inserted text
