### ISSUE TITLE
idea: Create `row` and `column` elements

### ISSUE THREAD

**Issue by tigerros** [marc2332/freya#409]
`row` would be `rect` with a horizontal direction, and `column` would be `rect` with a vertical direction. This would make the UI tree much easier to read. Although I feel like there's a reason why this isn't already implemented, because it's very common use case, and a very simple feature.

**Comment by tigerros** [comment]
I do think it's worth it. I tried Flutter and it would've been quite a bit more annoying if I had to specify the direction of the containers. It just seems weird to have rows/columns as the primary way to layout stuff, but having to use them through a property.

> As elements or as components?

Elements.

**Comment by marc2332** [comment]
Would you still keep `rect` ?

**Comment by tigerros** [comment]
Yes, but I would modify it to be allowed to have only one child, just like `Container` in Flutter.

**Comment by tigerros** [comment]
Can't you just make a `child: Element` property instead of `children: Element`?

**Comment by marc2332** [comment]
> Can't you just make a `child: Element` property instead of `children: Element`?

No, `Element`s in Dioxus can have multiple elements

**Comment by OlshaMB** [comment]
Why do we need multiple elements, when we can have one that houses all properties, row and columns are just directions of a flex layout, not entirely new components that have entirely new meaning, but I like the idea of separating flex properties to a new `flex` element. I could edit the rfc on flexes with that(#327)

**Comment by tigerros** [comment]
It makes the UI easier to read and edit. We could remove all elements and components and make them properties in one huge element, but we obviously don't do that, because each element would look the same and you would need to write an insane amount of properties. Among various other reasons. This is a similar scenario, just scaled down.

**Comment by OlshaMB** [comment]
I suggested `flex` element that separates all flex things into a separate element, row and column do not have entirly new properties, in fact they have the same properties, so no need to separate. You could make row and column **components** with rect. Also having different elements makes switching direction with state easily impossible, it forces you to have a condition and a separate component.

**Comment by tigerros** [comment]
> Also having different elements makes switching direction with state easily impossible, it forces you to have a condition and a separate component.

I didn't think of that... Yeah, in that case two elements would be bad.
