### ISSUE TITLE
enhancement: More flexible built-in component styling

### ISSUE THREAD

**Issue by tigerros** [marc2332/freya#423]
I noticed that the built-in components don't have very good style configuration. There's PRs like [#422](https://github.com/marc2332/freya/pull/422) that add more style properties to components, but I  think that's not sustainable. Could there be a better way than just adding more style properties? Maybe a stylesheet?

**Comment by marc2332** [comment]
That's what Themes are for, they are kind of a stylesheet. Although they mostly contain visual styling and not layout styling, perhaps I could also move the layout styling (margin, padding, etc) to Themes? What do you think?

**Comment by tigerros** [comment]
> That's what Themes are for, they are kind of stylesheets.

Using themes is annoying when you try to change the style of just one component instead of the entire app or all of the `render!` macro contents. I think components could have an optional `theme` property that would override the inherited theme. For example:

```rust
render! {
    Button {
        theme: ButtonTheme {
            background: "red",
            ..LIGHT_THEME.button
        }
    }
}
```

> I could also add the layout styling (margin, padding, etc) to Themes (beside passing via prop)? What do you think?

Yeah I think layout should be in the themes. The split is pretty arbitrary, and it doesn't seem to be followed properly :P (#422 added `shadow` and `corner_radius` properties which are not layout) And if you go forward with my `theme` property suggestion, it would also mean that all style properties would be separated from the "functional" properties.

I also want to point out that the components don't fully utilize themes. As in, there's some properties which just have a hardcoded value (e.g., `border` is always `1 solid` in `Input`). That's not really an API issue though.

**Comment by marc2332** [comment]
> ```rust
> render! {
>     Button {
>         theme: ButtonTheme {
>             background: "red",
>             ..LIGHT_THEME.button
>         }
>     }
> }
> ```

Yeah, I think I like that, I'll see what I can do



> Yeah I think layout should be in the themes. The split is pretty arbitrary, and it doesn't seem to be followed properly :P (#422 added `shadow` and `corner_radius` properties which are not layout) And if you go forward with my `theme` property suggestion, it would also mean that all style properties would be separated from the "functional" properties.

You are 💯 right

> I also want to point out that the components don't fully utilize themes. As in, there's some properties which just have a hardcoded value (e.g., `border` is always `1 solid` in `Input`). That's not really an API issue though.

I also noticed this yesterday when doing https://github.com/marc2332/freya/pull/422

**Comment by tigerros** [comment]
> Yeah, I think I like that, I'll see what I can do

I would be happy to make a PR
