### ISSUE TITLE
enhancement: Test book in workflow

### ISSUE THREAD

**Issue by tigerros** [marc2332/freya#427]
The book has a lot of code that doesn't even compile. Testing the UI is overkill, but the book should not contain any code that doesn't compile.

**Comment by marc2332** [comment]
Some examples are intentionally simplified, so if you just copy and paste them, they will obviously not compile.

**Comment by tigerros** [comment]
They're part of what I meant, yes. I'm not sure if hiding lines with `#` is possible in mdbook, but that's what I'm proposing. I think adding `# use freya::prelude::*;` and some other imports would make most of the book compile. The problem is that right now, the book might be outdated, but you would need to manually check each code block to see if it is. It's what the Rust book uses.

**Comment by marc2332** [comment]
Ahh, sure, sgtm
