### ISSUE TITLE
`font_width` attribute has no effect

### ISSUE THREAD

**Issue by tigerros** [marc2332/freya#451]
This:

```rust
render! {
  label {
    font_width: "ultra-expanded",
    "Test"
  }
}
```

Looks the same as this:

```rust
render! {
  label {
    font_width: "normal", // font_weight can also be omitted, no effect
    "Test"
  }
}
```

**Comment by marc2332** [comment]
You just need to use variable-width font. `font_weight` works just fine

**Comment by tigerros** [comment]
> You just need to use variable-width font. `font_weight` works just fine

What's an example of a font like that?

**Comment by marc2332** [comment]
> > You just need to use variable-width font. `font_weight` works just fine
> 
> What's an example of a font like that?

I don't know right now, but I don't think they are very common, I think the most common type usually supports weight and maybe slant
