### ISSUE TITLE
When using tokio to do asynchronous operations, the window will freeze

### ISSUE THREAD

**Issue by WZY1999428** [marc2332/freya#463]
Hello, when I use tokio, I just add the tokio attribute in the main function and dynamically render a simple list. After a while, the window will freeze.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
use freya::prelude::*;
#[tokio::main]
async fn main() {
    launch(app);
}
// 创建窗口
fn app(cx: Scope) -> Element {
    let labels = [1, 2, 3, 4, 5].iter().map(|name| {
        rsx!(rect {
            background: "blue",
            height: "100",
            width: "100%",
            margin:"10 0 0 0",
            label{"{name}"}
        })
    });
    render!(ScrollView {
        height: "100%",
        width: "100%",
        show_scrollbar: true,
        labels
    })
}

![image](https://github.com/marc2332/freya/assets/48763949/bbd0dbb9-3f2d-4d64-a01b-039ef33aa7b8)

**Comment by marc2332** [comment]
The problem is that Freya also creates it's own tokio runtime internally. I could make it optional (but enabled by default), so users can decide whether to run it's own tokio runtime if they want, via a crate feature

**Comment by WZY1999428** [comment]
Yes, I think developers can configure it, or they can use Freya's built-in tokio

**Comment by WZY1999428** [comment]
Yes, I think developers can configure it, or they can use Freya's built-in tokio
