### ISSUE TITLE
Compiling failed!

### ISSUE THREAD

**Issue by sanrentai** [marc2332/freya#469]
error: linking with `link.exe` failed: exit code: 1120
note: skunicode.lib(icu.SkLoadICU.obj) : error LNK2019: 无法解析的外部符号 __std_init_once_link_alternate_names_and_abort，函数 "bool __cdecl SkLoadICU(void)" (?SkLoadICU@@YA_NXZ) 中引用了该符号
          skunicode.lib(icu.umutex.obj) : error LNK2001: 无法解析的外部符号 __std_init_once_link_alternate_names_and_abort
          skia.lib(skia.SkSLRasterPipelineBuilder.obj) : error LNK2019: 无法解析的外部符 号 __std_max_element_2，函数 "public: void __cdecl SkSL::RP::Program::dump(class SkWStream *)const " (?dump@Program@RP@SkSL@@QEBAXPEAVSkWStream@@@Z) 中引用了该符号
          skia.lib(skia.SkSLRasterPipelineBuilder.obj) : error LNK2019: 无法解析的外部符 号 __std_max_element_1，函数 "public: void __cdecl SkSL::RP::Program::dump(class SkWStream *)const " (?dump@Program@RP@SkSL@@QEBAXPEAVSkWStream@@@Z) 中引用了该符号
          skia.lib(gpu.GrGLCaps.obj) : error LNK2019: 无法解析的外部符号 __std_find_trivial_4，函数 "public: bool __cdecl GrGLCaps::programBinaryFormatIsValid(unsigned int)const " (?programBinaryFormatIsValid@GrGLCaps@@QEBA_NI@Z) 中引用了该符号
          skia.lib(skia.SkSLFindAndDeclareBuiltinFunctions.obj) : error LNK2019: 无法解析的外部符号 __std_find_trivial_8，函数 "void __cdecl SkSL::Transform::FindAndDeclareBuiltinFunctions(struct SkSL::Program &)" (?FindAndDeclareBuiltinFunctions@Transform@SkSL@@YAXAEAUProgram@2@@Z) 中引用了该符号
          skia.lib(skia.SkSLFindAndDeclareBuiltinVariables.obj) : error LNK2001: 无法解析的外部符号 __std_find_trivial_8
          skia.lib(skia.SkNWayCanvas.obj) : error LNK2001: 无法解析的外部符号 __std_find_trivial_8
          D:\rust\freya-app\target\debug\deps\freya_app.exe : fatal error LNK1120: 5 个无法解析的外部命令
error: could not compile `freya-app` (bin "freya-app") due to previous error

**Comment by marc2332** [comment]
Have you installed the `Desktop Development with C++` pack from Visual Studio 2022?

**Comment by sanrentai** [comment]
Thank you

**Comment by marc2332** [comment]
You are welcome!
