### ISSUE TITLE
idea: Add `onrightclick` and `onmiddleclick` events

### ISSUE THREAD

**Issue by tigerros** [marc2332/freya#519]
Right now it's very annoying to detect a left click, and unfortunately a left click is probably the most common event you want to detect. You have to subscribe to `onclick` but then pattern match the `MouseButton` of the event `MouseData`. I think there should be separate events for left clicks, right clicks and middle "clicks" with a separate struct similar to `MouseData` but with the `trigger_button` field removed.

There's also "forward", "back" and "other" variants of `MouseButton`, but I don't even know what those are and apparently it's not supported everywhere so I don't think those need their own event.

**Comment by marc2332** [comment]
`onleftclick` should probably just be `onclick` but only trigger on left clicks, adding `onrightclick` and `onmiddleclick` sounds nice, although I am not sure about the names, after this, `trigger_button` could be removed

**Comment by marc2332** [comment]
> > `onleftclick` should probably just be `onclick` but only trigger on left clicks, adding `onrightclick` and `onmiddleclick` sounds nice, although I am not sure about the names, after this, `trigger_button` could be removed
> 
> In some very specific cases developers may want to detect the `Forward`, `Back` and `Other(u16)` variants of the `trigger_button`, which might be a reason to keep `onclick` generic with `trigger_button`. Or just create `onforwardclick` and `onbackclick` but I don't know what `Other(u16)` is supposed to represent.

you can still use `onpointerup` for that

**Comment by marc2332** [comment]
Awesome, will do this change soon
