### ISSUE TITLE
docs: Copy some content of the upcoming 0.2 blog post to the docs

### ISSUE THREAD

**Issue by tigerros** [marc2332/freya#584]
Once https://github.com/marc2332/freya/pull/376 is finished, we should copy some of the things in the blog post over to the docs. For example, [`ActivableRoute`](https://docs.freyaui.dev/freya/components/fn.ActivableRoute.html) and [`use_activable_route`](https://docs.freyaui.dev/freya/hooks/fn.use_activable_route.html) have lackluster docs, but the blog post goes into a lot more details + examples.

**Comment by marc2332** [comment]
sounds like a good idea 😄
