### ISSUE TITLE
bug: tab key is not listened with `onkeydown` and `onkeyup`

### ISSUE THREAD

**Issue by ZeroX-DG** [marc2332/freya#586]
For some reason the tab key is not listened by the `onkeydown` and `onkeyup` event handler. Every other key worked tho, so it's quite strange.

**Comment by ZeroX-DG** [comment]
Ah so it's not that it's not listened. It's used to detect navigation within the app 

https://github.com/marc2332/freya/blob/1b1eb3ea7179dfc3b1840f9ba306c4e58d7ca4b1/crates/renderer/src/event_loop.rs#L147-L148

This prevented tab being treated as a real key input 😢

**Comment by marc2332** [comment]
> Ah so it's not that it's not listened. It's used to detect navigation within the app
> 
> https://github.com/marc2332/freya/blob/1b1eb3ea7179dfc3b1840f9ba306c4e58d7ca4b1/crates/renderer/src/event_loop.rs#L147-L148
> 
> This prevented tab being treated as a real key input 😢

Yeah... I am aware of this but I haven't found a decent way yet to detect when to do one thing or another

I have thought about doing it with the Dioxus event propagation system but haven't tried yet

**Comment by marc2332** [comment]
Let me try

**Comment by marc2332** [comment]
Just opened https://github.com/marc2332/freya/pull/587 @ZeroX-DG 

I made the keyboard navigation work if the highest `onkeydown` doesn't stop the propagation of the event

It's not perfect but I think it's better

**Comment by ZeroX-DG** [comment]
Yeah the PR is more like allowing tab key event to go through & perform navigation at the same time. (I'm just guessing, I'm not really familiar with freya codebase haha)

I think it's closer to the behaviour on the web that way since the JS way is to allow tab key & navigation to happen at the same time & you should call `event.preventDefault()` if you don't want navigation to happen.

**Comment by marc2332** [comment]
I have come up with a `prevent_navigation` method for the `use_focus` hook which should indeed prevent any navigation no matter where you call it from

**Comment by marc2332** [comment]
I have yet to actually test it but I think it should work

**Comment by ZeroX-DG** [comment]
I've just tested it by adding these two lines in `password` example:

![Screenshot 2024-04-26 at 1 04 30 AM](https://github.com/marc2332/freya/assets/12984316/7ad1797c-7adb-40f2-8bdc-3d91dd82f6c7)

Works great! You probably want to start handling the Tab key event in places like `use_editable` too, so it insert a `\t` for Input & Textarea.

**Comment by ZeroX-DG** [comment]
You can then support indenting lines in valin editor! 😄

**Comment by marc2332** [comment]
> I've just tested it by adding these two lines in `password` example:
> 
> ![Screenshot 2024-04-26 at 1 04 30 AM](https://private-user-images.githubusercontent.com/12984316/325618237-7ad1797c-7adb-40f2-8bdc-3d91dd82f6c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTEzMjUsIm5iZiI6MTcxNDA1MTAyNSwicGF0aCI6Ii8xMjk4NDMxNi8zMjU2MTgyMzctN2FkMTc5N2MtN2FkYi00MGYyLThiZGMtM2Q5MWRkODJmNmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZGQ5ODBkOGJmMzFmNTA1MTM0MDg4YzhlMjUzMjBkNjYyYjEyOTQ3NmQwMjFiZTAzYjEzMWQxNTM0M2E2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HyV4HqcsL0jcGAHnsLe4S2BA9dz9zhR-8B6whDPLNH0)
> 
> Works great! You probably want to start handling the Tab key event in places like `use_editable` too, so it insert a `\t` for Input & Textarea.

Heads up: prevent_navigation is meant to be used inside of `onkeydown` events 😄. I will add some docs and tests asap!

**Comment by marc2332** [comment]
> You can then support indenting lines in valin editor! 😄

yeees! 🤣

**Comment by ZeroX-DG** [comment]
Ah yeah, I was just too lazy to make the `onkeydown` handler hahaha.

That was a really fast fix! Thank you for the awesome work!
