### ISSUE TITLE
request: use_node_size hook

### ISSUE THREAD

**Issue by ZeroX-DG** [marc2332/freya#590]
Maybe have a hook for retrieving the node size whenever torin finished layouting.

Basically, I'm trying to detect my component resizing but freya doesn't send the window resize event as a `PlatformEvent` and also I'd have to manually calculate my component size afterward so I think having a `use_node_size` that emit the component size whenever it changes would be really useful.

**Comment by marc2332** [comment]
That's exactly what `use_node` does

**Comment by marc2332** [comment]
https://github.com/marc2332/freya/blob/main/examples/min_max_sizing.rs

**Comment by ZeroX-DG** [comment]
Hmm okay. I was having trouble trying to log out the size of the node inside my `use_effect`. Turns out it only trigger when you include the size in the rendering code.

```
fn app() -> Element {
    let (node_ref, size) = use_node_signal();
    use_effect({
        move || {
            println!("{:?}", size().area.width()); // This won't print every time I resize
        }
    });
    rsx!(
        rect {
            width: "50%",
            height: "50%",
            min_width: "200",
            min_height: "100",
            max_width: "300",
            max_height: "250",
            background: "black",
            reference: node_ref,
            label {
                color: "white",
                // "Size: {size().area.width()}x{size().area.height()}"
            }
        }
    )
}
```

```
fn app() -> Element {
    let (node_ref, size) = use_node_signal();
    use_effect({
        move || {
            println!("{:?}", size().area.width()); // This will print
        }
    });
    rsx!(
        rect {
            width: "50%",
            height: "50%",
            min_width: "200",
            min_height: "100",
            max_width: "300",
            max_height: "250",
            background: "black",
            reference: node_ref,
            label {
                color: "white",
                "Size: {size().area.width()}x{size().area.height()}"
            }
        }
    )
}
```

**Comment by marc2332** [comment]
> Hmm okay. I was having trouble trying to log out the size of the node inside my `use_effect`. Turns out it only trigger when you include the size in the rendering code.
> 
> ```rust
> fn app() -> Element {
>     let (node_ref, size) = use_node_signal();
>     use_effect({
>         move || {
>             println!("{:?}", size().area.width()); // This won't print every time I resize
>         }
>     });
>     rsx!(
>         rect {
>             width: "50%",
>             height: "50%",
>             min_width: "200",
>             min_height: "100",
>             max_width: "300",
>             max_height: "250",
>             background: "black",
>             reference: node_ref,
>             label {
>                 color: "white",
>                 // "Size: {size().area.width()}x{size().area.height()}"
>             }
>         }
>     )
> }
> ```
> 
> ```rust
> fn app() -> Element {
>     let (node_ref, size) = use_node_signal();
>     use_effect({
>         move || {
>             println!("{:?}", size().area.width()); // This will print
>         }
>     });
>     rsx!(
>         rect {
>             width: "50%",
>             height: "50%",
>             min_width: "200",
>             min_height: "100",
>             max_width: "300",
>             max_height: "250",
>             background: "black",
>             reference: node_ref,
>             label {
>                 color: "white",
>                 "Size: {size().area.width()}x{size().area.height()}"
>             }
>         }
>     )
> }
> ```

That is actually a Dioxus bug I believe

https://github.com/DioxusLabs/dioxus/issues/2347

**Comment by marc2332** [comment]
Let me see if I can get around it

**Comment by marc2332** [comment]
@ZeroX-DG I can't fix it from Freya but there is a workaround for you I actually use in some places

Use `use_memo` instead of `use_effect`

```rs
fn app() -> Element {
    let (node_ref, size) = use_node_signal();
    use_memo(move || {
        println!("{:?}", size().area.width()); // This won't print every time I resize
    });
    rsx!(
        rect {
            width: "50%",
            height: "50%",
            min_width: "200",
            min_height: "100",
            max_width: "300",
            max_height: "250",
            background: "black",
            reference: node_ref,
            label {
                color: "white",
                // "Size: {size().area.width()}x{size().area.height()}"
            }
        }
    )
}
```

**Comment by ZeroX-DG** [comment]
That works great. I spent an hour trying to find out why it's not logging haha.

I think that solved my issue. I'll close this issue. Thank you for the fast respond!

**Comment by marc2332** [comment]
Awesome 😄
