### ISSUE TITLE
enhancement: `use_window` hook

### ISSUE THREAD

**Issue by ZeroX-DG** [marc2332/freya#595]
I'm working on a frameless window and I want to define a region that user can click on a drag the window around using that region.

This require access to the winit window and call [`drag_window()`](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.drag_window). Would be nice if I can access the window via a `use_window` hook and do something like this:

```rs
#[component]
fn App() -> Element {
  const window = use_window();

  rsx!(
    rect {
      width: "100%",
      height: "50",
      onmousedown: |_| window.drag_window()
    }
  )
}
```

**Comment by marc2332** [comment]
Probably makes more sense to add this features into `use_platform`

**Comment by ZeroX-DG** [comment]
Yeah, that's perhaps a better place for it.

We'll also have to think about cases where there are multiple windows too.

**Comment by marc2332** [comment]
Or maybe it's fine being at user level, I guess it's worth trying as well

**Comment by ZeroX-DG** [comment]
Hmm now that I read the code. I think we should support things from the framework level & not letting user having access to the window. Because that require wrapping the window in `Arc<Mutex<..>>` so it can be accessed outside the event loop. It just add more complexity & ways to create error.

**Comment by marc2332** [comment]
Yeah, that's why I use event loop messages for that kind of thing, it's less error-prone

**Comment by marc2332** [comment]
It also makes it less-dependent in the window concept

**Comment by ZeroX-DG** [comment]
> It also makes it less-dependent in the window concept
Yeah that's a good point. I'll close this issue then.
