### ISSUE TITLE
enhancement: Expose scale factor in PlatformInformation

### ISSUE THREAD

**Issue by ZeroX-DG** [marc2332/freya#605]
We should expose the window scaling factor as part of `PlatformInformation` so user can manually do the scaling in their canvas.

**Comment by ZeroX-DG** [comment]
Just realised https://github.com/marc2332/freya/issues/270 exist 🤦 I'll rename this.

**Comment by marc2332** [comment]
Yeah, I actually tried to get automatic scale factor to work a while ago, but I couldn't make it work, worth revisiting

**Comment by marc2332** [comment]
Yeah, exposing the scale factor is definitely a good idea, shouldn't be too hard either

**Comment by marc2332** [comment]
Started working on https://github.com/marc2332/freya/pull/606, I'll get it working soon

**Comment by marc2332** [comment]
Can you @ZeroX-DG and see if it now reacts properly when you move it through windows? I have yet to add it to PlatFormInformation tho

**Comment by marc2332** [comment]
Just opened https://github.com/marc2332/freya/pull/607
