### ISSUE TITLE
issue: Unexpected layout

### ISSUE THREAD

**Issue by seppelin** [marc2332/freya#698]
If you run this code:
```
fn main() {
    launch(app);
}

fn app() -> Element {
    rsx!(rect {
        width: "100%",
        height: "100%",
        direction: "horizontal",
        main_align: "end",
        X{}
        Y{}
    })
}

#[component]
fn X() -> Element {
    rsx!(rect {
        background: "blue",
        width: "fill",
        height: "fill",
        label {
            "HELOOOOOOOOOOOOOOOOOOOOOOoeoeoeoeoeeoeoeo"
        }
    })
}

#[component]
fn Y() -> Element {
    rsx!(rect {
        background: "red",
        width: "300",
        height: "fill",
    })
}
```
The layout of X{} is off by a big margin. You can only read the last latters of HELOO...
If you remove main_align and change the order of x and y it disappears, even though it should be the same effekt  just mirrored.

**Comment by marc2332** [comment]
Hey! It's not wrong, notice how the `X` component has a `fill` width, this means that it will take all the remaining space to the right, effectively ignoring the size of `Y`.

If you swap `X` and `Y` width it will work just fine:

```rs
fn main() {
    launch(app);
}

fn app() -> Element {
    rsx!(rect {
        width: "100%",
        height: "100%",
        direction: "horizontal",
        main_align: "end",
        X{}
        Y{}
    })
}

#[component]
fn X() -> Element {
    rsx!(rect {
        background: "blue",
        width: "300",
        height: "fill",
        label {
            "HELOOOOOOOOOOOOOOOOOOOOOOoeoeoeoeoeeoeoeo"
        }
    })
}

#[component]
fn Y() -> Element {
    rsx!(rect {
        background: "red",
        width: "fill",
        height: "fill",
    })
}
```

![image](https://github.com/marc2332/freya/assets/38158676/9e73988e-58f5-4ec8-b91a-05afbdca3457)

But, this obviously changes the result, for an actual working code that follows the same idea as yours it would be something like the following:

```rs
fn main() {
    launch(app);
}

fn app() -> Element {
    rsx!(rect {
        width: "100%",
        height: "100%",
        direction: "horizontal",
        main_align: "end",
        X{}
        Y{}
    })
}

#[component]
fn X() -> Element {
    rsx!(rect {
        background: "blue",
        width: "calc(100% - 300)",
        height: "fill",
        label {
            "HELOOOOOOOOOOOOOOOOOOOOOOoeoeoeoeoeeoeoeo"
        }
    })
}

#[component]
fn Y() -> Element {
    rsx!(rect {
        background: "red",
        width: "300",
        height: "fill",
    })
}
```

![image](https://github.com/marc2332/freya/assets/38158676/4df47b59-8f4b-454e-ad1f-20e5cf5aa582)

`fill` size should only (most of the case at least) be used for the last elements, using it before the last element will cause weird behaviors as you shared. A solution is to use `calc()` like I did in the second example, it's not perfect but it works for this. A perfect solution would be to have a more flex-like layout supported

**Comment by seppelin** [comment]
Thank you for clearification. Flex like layout would be really cool
