### ISSUE TITLE
enhancement: Support `alpha` channel in `AnimColor`

### ISSUE THREAD

**Issue by Aiving** [marc2332/freya#770]
The current implementation of `AnimColor` returns (and animates) only RGB when calling `as_string`, even if in `origin` or `destination` properties the `alpha` channel value is not 255.

https://github.com/marc2332/freya/blob/1955629e6c355ff74415037e44869026da8aec89/crates/hooks/src/use_animation.rs#L180-L187

**Comment by marc2332** [comment]
Very good point. I'll improve this asap!

**Comment by marc2332** [comment]
Just opened https://github.com/marc2332/freya/pull/771
