### ISSUE TITLE
bug: App gets frozen when using a custom Tokio runtime

### ISSUE THREAD

**Issue by reyamir** [marc2332/freya#779]
**Description**:
Add `custom-tokio-rt` to Cargo features. Then create simple app:
```rust
#[tokio::main]
async fn main() {
    launch_with_title(|| rsx!(label { "Hello, World!" }), "Custom Tokio Runtime")
}
```
And run app like normally, after few seconds CPU usage will spike to very high cause app hang forever.

Reprocedue repo: https://github.com/reyamir/macos-app-stuck

<img width="925" alt="Screenshot 2024-07-11 at 15 42 59" src="https://github.com/marc2332/freya/assets/123083837/023f5286-8cf2-4a45-bcb7-07446ac3f898">

**Comment by marc2332** [comment]
Seems to also affect Linux, but not Windows

**Comment by marc2332** [comment]
Can you try with:

```rs
fn main() {
    let rt = tokio::runtime::Builder::new_multi_thread()
    .enable_all()
    .build()
    .unwrap();
    let _guard = rt.enter();
    launch_with_title(|| rsx!(label { "Hello, World!" }), "Custom Tokio Runtime")
}
```

**Comment by reyamir** [comment]
It still stuck after few seconds

**Comment by reyamir** [comment]
Oh sorry, I still use `#[tokio::main]` and async fn main
I've updated my code exactly like you, and it work fine now.

**Comment by marc2332** [comment]
Nice, just fixed the example in https://github.com/marc2332/freya/commit/ef35ad266d324325c5af95226eca819c912ac545
