### ISSUE TITLE
`rust-toolchain.toml` forces `windows-gnu` which causes `skia-bindings` build script to fail

### ISSUE THREAD

**Issue by EndilWayfare** [marc2332/freya#794]
This is only an issue when cloning and using the `freya` workspace directly. I have been using `freya` as a dependency for a bit, and that initial experience was painless and seamless. However, if anyone running examples or setting up to contribute on Windows will likely run into this problem.

This is a known limitation with `rust-toolchain.toml`, apparently. https://github.com/rust-lang/rustup/issues/3546
I tried to explicitly install `1.79.0-x86_64-pc-windows-msvc` toolchain, but it still overrides to `windows-gnu`.

It seems that the root issue is that `rust-skia` only supports [pre-built binaries for `x86_64-pc-windows-msvc` target](https://github.com/rust-skia/rust-skia?tab=readme-ov-file#platform-support-build-targets-and-prebuilt-binaries). First, it failed with a cryptic error about symlink failure (easily solved by turning on "Developer Mode" in Windows settings), but then `ninja` started failing with some deep-in-the-weeds build errors.

I could probably debug the build problems, but it was more immediately easy to just temporarily disable `rust-toolchain.toml`. Doing this, the examples built and ran without issue. I will likely put more effort into figuring this out when I get a chance, since I'd like to contribute to the project at some point.

I don't know what the best ultimate "fix" is here, but it's probably worth adding a small section to the README with a heads-up about this wrinkle and how to work around it.

**Comment by marc2332** [comment]
Hey! Interesting issue! I always used msvc so I never noticed this. Thanks for opening an issue, much appreciated.

What do you think about changing this part of the README:

```md
### Want to try it? 🤔

⚠️ First, see [Setup guide](https://book.freyaui.dev/setup.html).

Clone this repo and run:

```shell
cargo run --example counter
```

to

```md
### Want to try it? 🤔

👋 Make sure to check the [Setup guide](https://book.freyaui.dev/setup.html) first.

> ⚠️ If you happen to be on Windows using `windows-gnu` and get compile errors, maybe go check this [issue](https://github.com/marc2332/freya/issues/794).

Clone this repo and run:

```shell
cargo run --example counter
```
```

**Comment by EndilWayfare** [comment]
That sounds like it would do the trick!

Yeah, I'm not sure why exactly my setup wants to default to `windows-gnu`, since I also near-exclusively use msvc. There was some crate I was using a while ago that required gnu, I think, and so now it's in my config somewhere. I guess? 🤷

**Comment by Maikel1963** [comment]
Sad to read this! For licensing reasons I have to stick with gnu toolchain. So I cannot use Freya as much as I would like to. Any chance that the dependency an MSVC may change in the near future?

**Comment by marc2332** [comment]
> Sad to read this! For licensing reasons I have to stick with gnu toolchain. So I cannot use Freya as much as I would like to. Any chance that the dependency an MSVC may change in the near future?

Unfortunately it seems to be what skia-safe provives by default on Windows, I suppose you could try manually building Skia by adding the env var `FORCE_SKIA_BINARIES_DOWNLOAD = 1`. I would suggest opening an issue in skia-safe's repo too
