### ISSUE TITLE
tracking: Events support

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#8]
This issue tracks the support for events.

- `onclick`
   - [x] implemented
   - [x] screen coordinates
   - [x] element coordinates
   - [x] global
- `onmousedown`
   - [x] implemented
   - [x] screen coordinates
   - [x] element coordinates
   - [x] global
-  `onmouseover`
   - [x] implemented
   - [x] screen coordinates
   - [x] element coordinates
   - [x] global
- `onmouseleave`
   - [x] implemented
   - [x] screen coordinates
   - [x] element coordinates
- `onmouseenter`
   - [x] implemented
   - [x] screen coordinates
   - [x] element coordinates
- `onmouseup`
   - [ ] implemented
   - [ ] screen coordinates
   - [ ] element coordinates
   - [ ] global
-  `onwheel`
   - [x] implemented
   - [x] y scroll
   - [x] x scroll
- `keydown`
   - [x] implemented
   - [x] Composable characters
   - [x] Modifiers
- `keyup`
   - [x] implemented
   - [x] Composable characters
   - [x] Modifiers
- `onglobalclick`
   - [x] implemented
   - [x] screen coordinates
 - `ontouchcancel`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Finger ID
   - [x] Force 
   - [ ] global
 - `ontouchend`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Finger ID
   - [x] Force 
   - [ ] global
 - `ontouchmove`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Finger ID
   - [x] Force 
   - [ ] global
 - `ontouchstart`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Finger ID
   - [x] Force 
   - [ ] global
 - `onpointerdown`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Mouse type
   - [x] Touch type
   - [ ] global
 - `onpointerup`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Mouse type
   - [x] Touch type
   - [ ] global
 - `onpointerover`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Mouse type
   - [x] Touch type
   - [ ] global
 - `onpointerenter`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Mouse type
   - [x] Touch type
 - `onpointerleave`
   - [x] screen coordinates
   - [x] element coordinates
   - [x] Mouse type
   - [x] Touch type

**Comment by Tropix126** [comment]
Should `onclick` also be fired along with touch events? From what i've seen, browsers typically treat the "click" event as an abstraction over a group of behaviors that could trigger something (for example, if enter or space is pressed while an element is focused).
![image](https://github.com/marc2332/freya/assets/42101043/d6647c5c-52be-48d5-b145-d8a1599f2cb0)

**Comment by marc2332** [comment]
> Should `onclick` also be fired along with touch events? From what i've seen, browsers typically treat the "click" event as an abstraction over a group of behaviors that could trigger something (for example, if enter or space is pressed while an element is focused). ![image](https://user-images.githubusercontent.com/42101043/239693141-d6647c5c-52be-48d5-b145-d8a1599f2cb0.png)

I also asked myself that question. I will see what other GUI libraries do 🤔 I just opened https://github.com/marc2332/freya/issues/201
