### ISSUE TITLE
enhancement: `spacing` attribute for `rect`

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#829]
Some kind of margin between elements that is defined by the parent. Like a gap.

```rs
rect {
	spacing: "4",
	Button {
    	label {
			"Hello"
		}
	}
	Button {
    	label {
			"Hello"
		}
	}
}
```

**Comment by hydra** [comment]
my use-case, for a spacer, is to take up the space between elements.  

![image](https://github.com/user-attachments/assets/e767d219-aec8-46a2-9138-a6c1298a8b66)

```
// container
rect {
  width: "100%",
  direction: "horizontal",
  // group 1
  rect {
    direction: "horizontal",
    Button { ... },
    Button { ... },
  }
  Spacer { ... }
  // group 2
  rect {
    direction: "horizontal",
    Button { ... },
    ...
  }
}
```
I specifically do not want to set any widths other than on the container.

**Comment by marc2332** [comment]
> my use-case, for a spacer, is to take up the space between elements.
> 
> ![image](https://private-user-images.githubusercontent.com/57075/363294853-e767d219-aec8-46a2-9138-a6c1298a8b66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDM2NTQsIm5iZiI6MTcyNTA0MzM1NCwicGF0aCI6Ii81NzA3NS8zNjMyOTQ4NTMtZTc2N2QyMTktYWVjOC00NmEyLTkxMzgtYTZjMTI5OGE4YjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE4NDIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZmMxYjhlYzk1OTMzZTMzMjNkNDJmYThiZjBhNmE4ZjIxNzYzMTNkYTNkMTZjYmY4OGIyOGI0ZGUzMzMyY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iwMyG_D2l0FhVfY1oK2_Gx9TLM7K4x0rah_aE199iwk)
> 
> ```
> // container
> rect {
>   width: "100%",
>   direction: "horizontal",
>   // group 1
>   rect {
>     direction: "horizontal",
>     Button { ... },
>     Button { ... },
>   }
>   Spacer { ... }
>   // group 2
>   rect {
>     direction: "horizontal",
>     Button { ... },
>     ...
>   }
> }
> ```
> 
> I specifically do not want to set any widths other than on the container.

You can actually get this behavior by using the alignment attributes:

```rs
rsx!(
    rect {
        direction: "horizontal",
        Button {
            label {
                "Hello, World 1!"
            }
        }
        Button {
            label {
                "Hello, World 2!"
            }
        }
        rect {
            width: "fill", // Take the available space
            direction: "horizontal",
            main_align: "end", // Align the inner children to the end
            Button {
                label {
                    "Hello, World 3!"
                }
            }
        }
    }
)
```

![image](https://github.com/user-attachments/assets/0dfc00c5-11f9-430e-b59d-c76d1bf80429)
