### ISSUE TITLE
bug: `onclick` should only be emitted to the element it was started on and not where it finished

### ISSUE THREAD

**Issue by maiadere** [marc2332/freya#849]
`Button` component only handles `onpointerup` event: https://github.com/marc2332/freya/blob/f7f214001f3bd5b8fa995f3bd06b12287e2f49b0/crates/components/src/button.rs#L174

Adding `onpointerdown` and storing some state to check if mouse button was pressed on the button would fix it.

Example:

https://github.com/user-attachments/assets/af2ab8a1-d524-4aef-9a6f-9d4563a36e34

**Comment by marc2332** [comment]
This is more of a general issue, I actually had a fix of this in another PR but I ended up closing it because of other reasons, I should bring it back.
