### ISSUE TITLE
question: Support for common text editing shortcuts

### ISSUE THREAD

**Issue by fanbal** [marc2332/freya#861]
My version is freya  "0.2" ,  usage experiement of Component Input is not good. It's hard to find hotkey and contextmenu in input.
Ctrl+C: copy
Ctrl+V: paste
Ctrl+A: select all text

**Comment by marc2332** [comment]
Have you tried the git version? I implemented those shortcuts a while ago

**Comment by marc2332** [comment]
About the context menu, I don't have that yet.

**Comment by fanbal** [comment]
> Have you tried the git version? I implemented those shortcuts a while ago
My version is installed from cargo, there is something obsolet ,like still use `onclick` but not `onpress`.
Well, i will try use git refresh version.XD

**Comment by fanbal** [comment]
shortcuts  supported in current git version
