### ISSUE TITLE
Some minor errors occurred while compiling examle\i18n.rs

### ISSUE THREAD

**Issue by gqf2008** [marc2332/freya#876]
The project was updated very quickly 😄.

error[E0432]: unresolved import `dioxus_i18n::t`
 --> examples\i18n.rs:8:5
  |
8 |     t,
  |     ^ no `t` in the root

error[E0425]: cannot find function `i18n` in this scope
  --> examples\i18n.rs:19:20
   |
19 |     let mut i18n = i18n();
   |                    ^^^^ not found in this scope

**Comment by marc2332** [comment]
Is it possible that you cloned the repo a few days ago? I made a breaking change in dioxus-i18n in a patch release ( I know ).

Try `cargo update` and run it again

**Comment by gqf2008** [comment]
Okay, done. Thanks!

**Comment by marc2332** [comment]
Nice 😄
