### ISSUE TITLE
What methods can make the window display again?

### ISSUE THREAD

**Issue by gqf2008** [marc2332/freya#885]
Is there a way to make the window visible again after I set it to be invisible when the application starts?

**Comment by gqf2008** [comment]
The code below seems to work.

let platform = use_platform();
    spawn_forever(async move {
       loop {
        tokio::time::sleep(Duration::from_secs(5)).await;
        platform.with_window(|w|{
            w.set_visible(!w.is_visible().unwrap_or_default());
        });
       }
    });

**Comment by marc2332** [comment]
> The code below seems to work.
> 
> ```rust
> let platform = use_platform();
> spawn_forever(async move {
>    loop {
>     tokio::time::sleep(Duration::from_secs(5)).await;
>     platform.with_window(|w|{
>         w.set_visible(!w.is_visible().unwrap_or_default());
>     });
>    }
> });
> ```

Yes, bu why would you want to toggle the window invisibility every 5s? 😨

**Comment by marc2332** [comment]
Also make sure you spawn that task only once.

```rs
let platform = use_platform();
use_hook(|| {
	spawn_forever(async move {
	   loop {
	    tokio::time::sleep(Duration::from_secs(5)).await;
	    platform.with_window(|w|{
	        w.set_visible(!w.is_visible().unwrap_or_default());
	    });
	   }
	});
})
```

**Comment by gqf2008** [comment]
Yes, this is not a real scenario, just wanted to confirm the correct usage of the API. The real scenario on my side is like this, when triggered by the user to close the window, the system tray application is still running, the application doesn't really exit, and when the user clicks on the system tray icon the window is once again evoked.
