### ISSUE TITLE
bug: `mouseenter` gets emitted with touch data when there is touch movement

### ISSUE THREAD

**Issue by Tropix126** [marc2332/freya#887]
Source of the panic:
https://github.com/marc2332/freya/blob/1b1a24a84e2a80bffc3d439ae023cb9a812ec1b1/crates/elements/src/events/mouse.rs#L47
![image](https://github.com/user-attachments/assets/8ad8c8bc-1ff5-46c3-a464-9cfcf716d68f)

Steps to reproduce:
1. `cargo run --example=switch_theme`
2. Press the switch component with a touch input.
3. Panic occurs.

**Comment by marc2332** [comment]
https://github.com/marc2332/freya/pull/888 Should fix this
