### ISSUE TITLE
`ScrollView` does not consider bottom padding.

### ISSUE THREAD

**Issue by Tropix126** [marc2332/freya#893]
When using `ScrollView` with the `padding` prop set, the padding at the bottom will be cut short by the scroll.
```rs
    Body {
        ScrollView {
            padding: "96",

            // ...
        }
    }
)
```

https://github.com/user-attachments/assets/11bb8351-b99c-4c85-bdb3-98de9fe0880e

This seems to be due to a bad height calculation, and can be circumvented by adding a child `rect` with its own padding.

**Comment by marc2332** [comment]
Probably a bug on Torin if I were to guess
