### ISSUE TITLE
enhancement: corner_radius for shadow

### ISSUE THREAD

**Issue by ghost** [marc2332/freya#961]
Hi,

I have tried to add a `shadow` to a `rect` with a `corner_radius` and it looks like the shadow does not adopt to the `corner_radius`. What would be nice if either the `shadow` adopts  the `corner_radius` of the `rect` or if you could set it explicit on the  `shadow`.

**Comment by marc2332** [comment]
That would be nice indeed!

**Comment by marc2332** [comment]
Hey @vivi-rad shadows actually already follow the corner radius, at least on the main branch, are you perhaps on 0.2?
