### ISSUE TITLE
Media (Audio and Video) component Wanted

### ISSUE THREAD

**Issue by constlhq** [marc2332/freya#991]
Is it possible to play audio and vidio data with freya?

**Comment by marc2332** [comment]
Video? Easily no, maybe by drawing to the canvas you could get it to work, but its probably not easily

Audio? There is no api in freya for that but afaik there are lots of rust crates for that, right?

**Comment by constlhq** [comment]
Thanks for advice, I thought there may be a video component out of the box, just like video tag in html.

**Comment by constlhq** [comment]
By the way, the camera example doesn't work correctly on my laptop. When it launches, the camera is turned on, but nothing displays in the app window, no error prints neither. I tested on windows 11 with rust version 1.81.
